services:
    millwright_filter.paginator:
        class: Millwright\FilterBundle\Paginator\KnpPaginator
        arguments:
             - @knp_paginator
             - @lexik_form_filter.query_builder_updater
             - @millwright_filter.registry
        tags:
            -  { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
